### ISSUE TITLE
short nparray not supported

### ISSUE THREAD

**Issue by UeFan** [sabjorn/NumpySocket#11]
Hi I found that if I try to send a very short np array such as np.array([1,1]), the server will not receive it. Is this a problem overall or just on my side? 

My solution for now is that I just send the repeated array of 100 times and it will be received successfully.

**Comment by sabjorn** [comment]
the socket has a buffer, you can change the size of the buffer on the `recv` call. In essence, if the buffer isn't filled, you won't get your data back (this is why you have to send the array a bunch of times because then it finally fills the buffer). 

`bufsize` is the size in bytes.

you can calculate how many bytes you need for the bufsize with:
```
x = np.array([1,1]) 
bufsize = x.size * x.itemsize
print(bufsize) # 16 bytes
```

for a 2 element `int64` array, the size of your buffer is 16 bytes
```conn.recv(bufsize=16)```

however, I just tried with `bufsize=32` and `bufsize=64` and both work fine. `bufsize=128` does not. Probably this is because there is extra data overhead with the way I bundle up a the numpy array.
